#!/usr/bin/env python3
"""
generate_report.py — Generate daily analysis report from trending data.
Simple rule-based analysis (AI-ready hook for future OpenAI/etc integration).
"""

import json
import os
from datetime import date
from pathlib import Path

FOCUS_AREAS = {
    "AI / Machine Learning / LLM": ["ai", "llm", "gpt", "language model", "neural", "deep learning", "transformer", "diffusion", "stable diffusion", "chatbot", "rag", "vector db"],
    "Developer Tools / CLI / IDE": ["cli", "tool", "devtool", "ide", "editor", "debugger", "profiler", "testing", "ci/cd", "pipeline", "build"],
    "Web Framework / Frontend": ["react", "vue", "angular", "svelte", "next", "nuxt", "astro", "vite", "webpack", "frontend", "web", "ui", "css", "html"],
    "Cloud / DevOps / Container": ["kubernetes", "k8s", "docker", "terraform", "ansible", "aws", "gcp", "azure", "devops", "cloud", "container", "serverless", "lambda"],
}

DOMAIN_KEYWORDS = {
    "ai": ["ai", "llm", "gpt", "language model", "neural", "deep learning", "transformer", "diffusion", "stable diffusion", "chatbot", "rag", "vector db", "embedding", "ollama", "vllm", "openai", "gemini", "claude"],
    "devtools": ["cli", "tool", "devtool", "ide", "editor", "debugger", "profiler", "testing", "ci/cd", "pipeline", "build tool", "lint", "formatter"],
    "web": ["react", "vue", "angular", "svelte", "next", "nuxt", "astro", "vite", "webpack", "frontend", "web framework", "ui", "css", "html", "tailwind", "bootstrap"],
    "cloud": ["kubernetes", "k8s", "docker", "terraform", "ansible", "aws", "gcp", "azure", "devops", "cloud native", "container", "serverless", "lambda", "helm", "istio"],
}


def classify_project(name, description):
    """Classify project into focus areas based on name + description."""
    text = (name + " " + description).lower()
    matched = []
    for area, keywords in FOCUS_AREAS.items():
        for kw in keywords:
            if kw.lower() in text:
                matched.append(area)
                break
    return list(set(matched)) if matched else ["Other"]


def rank_trending_repos(repos, min_stars=100):
    """Rank repos by star count, group by focus area."""
    ranked = sorted([r for r in repos if r["stars"] >= min_stars], key=lambda x: x["stars"], reverse=True)
    by_area = {area: [] for area in list(FOCUS_AREAS.keys()) + ["Other"]}
    for repo in ranked:
        areas = classify_project(repo["name"], repo["description"])
        for area in areas:
            if area in by_area and len(by_area[area]) < 10:
                by_area[area].append(repo)
    return ranked, by_area


def generate_markdown(today, repos, filtered_repos):
    """Generate markdown report."""
    ranked, by_area = rank_trending_repos(repos)

    lines = [
        f"# GitHub Trending Daily Report",
        f"**Date:** {today}",
        "",
        "## 📊 Summary",
        f"- Total trending repos analyzed: **{len(repos)}**",
        f"- Repos in target languages (Python/JS/TS/Rust/Go): **{len(filtered_repos)}**",
        "",
        "## 🔥 Top Stars Today",
        "",
    ]

    for repo in ranked[:10]:
        lang = f" `{repo['language']}`" if repo["language"] else ""
        stars = f"⭐ {repo['stars']:,}" + (f" (+{repo['today_stars']} today)" if repo["today_stars"] else "")
        lines.append(f"### [{repo['name']}](https://github.com/{repo['name']})")
        lines.append(f"{stars}{lang}")
        if repo["description"]:
            lines.append(f"> {repo['description']}")
        lines.append("")

    lines += ["## 📂 By Focus Area", ""]
    for area, area_repos in by_area.items():
        if area_repos:
            lines.append(f"### {area}")
            for repo in area_repos[:5]:
                lang = f" `{repo['language']}`" if repo["language"] else ""
                lines.append(f"- **[{repo['name']}](https://github.com/{repo['name']})** ⭐{repo['stars']:,}{lang} — {repo['description'][:80]}")
            lines.append("")

    lines += [
        "## 🕐 Notes",
        "- Report generated automatically by GitHub Researcher",
        "- Data source: [GitHub Trending](https://github.com/trending)",
        "- Analysis covers: Python, JavaScript, TypeScript, Rust, Go",
        "",
        "---",
        "*Auto-generated by [github-researcher](https://github.com/appcanmr/github-researcher)*",
    ]

    return "\n".join(lines)


def generate_html(today, repos, filtered_repos):
    """Generate HTML version of the report."""
    ranked, by_area = rank_trending_repos(repos)

    area_rows = ""
    for area, area_repos in by_area.items():
        if area_repos:
            items = "".join(
                f'<li><a href="https://github.com/{r["name"]}" target="_blank">{r["name"]}</a> '
                f'<span class="stars">⭐{r["stars"]:,}</span> '
                f'<span class="lang">{r["language"] or ""}</span> — {r["description"][:80]}</li>'
                for r in area_repos[:5]
            )
            area_rows += f'<section class="focus-area"><h3>{area}</h3><ul>{items}</ul></section>'

    top_repos = "".join(
        f'<div class="repo-card">'
        f'<a href="https://github.com/{r["name"]}" target="_blank" class="repo-name">{r["name"]}</a>'
        f'<div class="repo-meta">'
        f'<span class="stars">⭐ {r["stars"]:,}</span>'
        f'<span class="lang">{r["language"] or ""}</span>'
        f'</div>'
        f'<p class="desc">{r["description"]}</p>'
        f'</div>'
        for r in ranked[:10]
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GitHub Trending Report — {today}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; background: #0d1117; color: #e6edf3; padding: 2rem; }}
  .container {{ max-width: 1100px; margin: 0 auto; }}
  header {{ margin-bottom: 2rem; border-bottom: 1px solid #30363d; padding-bottom: 1rem; }}
  h1 {{ font-size: 1.8rem; color: #58a6ff; }}
  .date {{ color: #8b949e; margin-top: 0.3rem; }}
  .stats {{ display: flex; gap: 1.5rem; margin: 1rem 0; }}
  .stat {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 0.8rem 1.2rem; }}
  .stat-value {{ font-size: 1.5rem; font-weight: bold; color: #58a6ff; }}
  .stat-label {{ font-size: 0.8rem; color: #8b949e; }}
  h2 {{ margin: 1.5rem 0 1rem; color: #f0f6fc; border-left: 3px solid #58a6ff; padding-left: 0.7rem; }}
  .repo-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .repo-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; transition: border-color 0.2s; }}
  .repo-card:hover {{ border-color: #58a6ff; }}
  .repo-name {{ font-size: 1rem; font-weight: 600; color: #58a6ff; text-decoration: none; }}
  .repo-name:hover {{ text-decoration: underline; }}
  .repo-meta {{ display: flex; gap: 0.8rem; margin: 0.4rem 0; font-size: 0.85rem; }}
  .stars {{ color: #e3b341; }}
  .lang {{ color: #8b949e; }}
  .desc {{ font-size: 0.85rem; color: #8b949e; line-height: 1.4; }}
  .focus-area {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin-bottom: 1rem; }}
  .focus-area h3 {{ color: #58a6ff; margin-bottom: 0.8rem; font-size: 1.1rem; }}
  .focus-area ul {{ list-style: none; }}
  .focus-area li {{ padding: 0.4rem 0; border-bottom: 1px solid #21262d; font-size: 0.9rem; color: #8b949e; }}
  .focus-area li:last-child {{ border-bottom: none; }}
  .focus-area a {{ color: #58a6ff; text-decoration: none; }}
  .focus-area a:hover {{ text-decoration: underline; }}
  footer {{ margin-top: 2rem; text-align: center; color: #484f58; font-size: 0.8rem; }}
  .updated {{ color: #8b949e; margin-bottom: 0.5rem; font-size: 0.85rem; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>📊 GitHub Trending Daily Report</h1>
    <div class="updated">Generated: {today}</div>
  </header>

  <div class="stats">
    <div class="stat">
      <div class="stat-value">{len(repos)}</div>
      <div class="stat-label">Total Trending</div>
    </div>
    <div class="stat">
      <div class="stat-value">{len(filtered_repos)}</div>
      <div class="stat-label">Target Languages</div>
    </div>
  </div>

  <h2>🔥 Top Stars Today</h2>
  <div class="repo-grid">{top_repos}</div>

  <h2>📂 By Focus Area</h2>
  {area_rows}

  <footer>
    Auto-generated by <a href="https://github.com/appcanmr/github-researcher" style="color:#58a6ff">github-researcher</a>
    · <a href="daily/{today}.html" style="color:#58a6ff">View Raw Report</a>
  </footer>
</div>
</body>
</html>"""
    return html


def main():
    today = date.today().isoformat()
    data_file = f"daily/{today}.json"

    if not os.path.exists(data_file):
        print(f"Data file {data_file} not found. Run fetch_trending.py first.")
        sys.exit(1)

    with open(data_file, encoding="utf-8") as f:
        data = json.load(f)

    repos = data.get("repositories", [])
    filtered = data.get("filtered_repositories", [])

    # Generate markdown
    md = generate_markdown(today, repos, filtered)
    md_file = f"daily/{today}.md"
    Path(md_file).write_text(md, encoding="utf-8")
    print(f"Markdown report: {md_file}")

    # Generate HTML
    html = generate_html(today, repos, filtered)
    html_file = f"docs/daily/{today}.html"
    Path(html_file).write_text(html, encoding="utf-8")
    print(f"HTML report: {html_file}")

    # Update trend index
    update_trend_index(today, repos, filtered)

    print("Report generation complete.")


def update_trend_index(today, repos, filtered):
    """Update the trend index with latest data."""
    ranked, by_area = rank_trending_repos(repos, min_stars=50)

    sections = [f"## Trend Index\n\n*Last updated: {today}*\n"]
    sections.append("### Top 20 All-Time (from recent data)\n")
    for repo in ranked[:20]:
        sections.append(f"- [{repo['name']}](https://github.com/{repo['name']}) ⭐{repo['stars']:,} `{repo['language'] or 'N/A'}` — {repo['description'][:60]}")

    for area, area_repos in by_area.items():
        if area_repos:
            sections.append(f"\n### {area}\n")
            for repo in area_repos[:10]:
                sections.append(f"- [{repo['name']}](https://github.com/{repo['name']}) ⭐{repo['stars']:,}")

    Path("indexes/trend-index.md").write_text("\n".join(sections), encoding="utf-8")
    print("Trend index updated.")


if __name__ == "__main__":
    main()
